name: Test claif_cod

on:
  push:
    branches: [main]
    paths:
      - 'claif_cod/**'
      - '.github/workflows/claif_cod.yml'
  pull_request:
    branches: [main]
    paths:
      - 'claif_cod/**'
      - '.github/workflows/claif_cod.yml'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-claif_cod
  cancel-in-progress: true

jobs:
  quality:
    name: Code Quality (claif_cod)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: claif_cod
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Ruff lint
        uses: astral-sh/ruff-action@v3
        with:
          version: "latest"
          args: "check --output-format=github"
          src: "claif_cod"

      - name: Run Ruff Format
        uses: astral-sh/ruff-action@v3
        with:
          version: "latest"
          args: "format --check --respect-gitignore"
          src: "claif_cod"

  test:
    name: Test claif_cod
    needs: quality
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: claif_cod
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install UV
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"
          python-version: ${{ matrix.python-version }}
          enable-cache: true
          cache-suffix: claif_cod-${{ matrix.os }}-${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          uv pip install --system --upgrade pip
          uv pip install --system ".[test]"

      - name: Run tests with Hatch (Unix)
        if: runner.os != 'Windows'
        run: uvx hatch test

      - name: Run tests with Hatch (Windows)
        if: runner.os == 'Windows'
        run: uvx hatch test
        shell: cmd

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-claif_cod-${{ matrix.python-version }}-${{ matrix.os }}
          path: claif_cod/coverage.xml
          retention-days: 5

  build:
    name: Build claif_cod
    needs: test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: claif_cod
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install UV
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"
          python-version: "3.12"
          enable-cache: true

      - name: Install build tools
        run: uv pip install --system build hatchling hatch-vcs

      - name: Build distributions
        run: uv run python -m build --outdir dist

      - name: Upload distribution artifacts
        uses: actions/upload-artifact@v4
        with:
          name: claif_cod-dist-files
          path: claif_cod/dist/
          retention-days: 5